remove cirrus.yml file
# Conflicts:
#	.cirrus/run-iris.sh

diff --git a/.github/workflows/analyze.yml b/.github/workflows/analyze.yml
--- a/.github/workflows/analyze.yml
+++ b/.github/workflows/analyze.yml
@@ -137,7 +137,56 @@ jobs:
             vault_path: 'iris data.sqc-us'
     steps:
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-      - name: Run IRIS
+      - uses: jdx/mise-action@f8dfbcc150159126838e44b882bf34bd98fd90f3 # v2025.1.3
+        with:
+          version: 2025.1.3
+      - name: Download and Run IRIS
         env:
           SONAR_TARGET_URL: ${{ matrix.target.url }}
-        run: source .cirrus/run-iris.sh
+        run: |
+          set -euo pipefail
+
+          VERSION="[RELEASE]"
+
+          # Download IRIS JAR
+          HTTP_CODE=$(curl \
+            --write-out '%{http_code}' \
+            --location \
+            --remote-name \
+            --user "$ARTIFACTORY_PRIVATE_USERNAME:$ARTIFACTORY_ACCESS_TOKEN" \
+            "$ARTIFACTORY_URL/sonarsource-private-releases/com/sonarsource/iris/iris/$VERSION/iris-$VERSION-jar-with-dependencies.jar")
+
+          if [ "$HTTP_CODE" != "200" ]; then
+            echo "Download $VERSION failed -> $HTTP_CODE"
+            exit 1
+          else
+            echo "Downloaded $VERSION"
+          fi
+
+          # Function to run IRIS
+          run_iris() {
+            java \
+              -Diris.source.projectKey="org.sonarsource.html:html" \
+              -Diris.source.organization="sonarsource" \
+              -Diris.source.url="https://next.sonarqube.com/sonarqube" \
+              -Diris.source.token="$SONAR_SOURCE_IRIS_TOKEN" \
+              -Diris.destination.projectKey="SonarSource_sonar-html" \
+              -Diris.destination.organization="sonarsource" \
+              -Diris.destination.url="$SONAR_TARGET_URL" \
+              -Diris.destination.token="$SONAR_TARGET_IRIS_TOKEN" \
+              -Diris.dryrun=$1 \
+              -jar iris-[RELEASE]-jar-with-dependencies.jar
+          }
+
+          # Execute IRIS as dry-run first
+          echo "===== Execute IRIS as dry-run"
+          run_iris "true"
+          STATUS=$?
+
+          if [ $STATUS -ne 0 ]; then
+            echo "===== Failed to run IRIS dry-run"
+            exit 1
+          else
+            echo "===== Successful IRIS dry-run - executing IRIS for real."
+            run_iris "false"
+          fi
